# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build buy Spot

on:
  push:
    branches: [master]

jobs:

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
         npm link
         npm install  
      - name: Build packages
        run: |
          npm build
      - name: Running prettier
        run: npm run prettier
      - name: Running eslint
        run: npm run lint

  test:
    runs-on: ubuntu-latest
    strategy:
        matrix:
            node-version: [16.x]
    steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
              node-version: ${{ matrix.node-version }}
              cache: 'yarn'
        - name: Install dependencies
          run: |
              npm link
              npm install
        - name: Build packages
          run: |
              npm build
        - name: test
          run: npm run test -- --coverage --watchAll=false

     

  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
         npm link
         npm install  
      - name: Build packages
        run: |
          npm build
      - name: npm ci
        run: npm ci

  security:

    runs-on: ubuntu-latest

      strategy:
        matrix:
          node-version: [16.x]
          
      steps:
        - uses: actions/checkout@v2
        - name: Use Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v2
          with:
            node-version: ${{ matrix.node-version }}
            cache: "yarn"
        - name: Running audit check
            run: npm audit
            continue-on-error: true
     

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "yarn"
      - name: Install dependencies
        run: |
         npm link
         npm install  
      - name: Build packages
        run: |
          npm build
      - name: Upload production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Static Build folder
          path: |
            ./build





     
     
    
   

